# Define required paths for the MOUSE data pipeline
# Base directory for processing
vsi_root: "/Users/bpauw/Documents/BAM/Measurements/newMouseTest/"

# for testing, we set this to the location of the demo data tree.
saxs_dir: "/Users/bpauw/Documents/BAM/Measurements/newMouseTest/Measurements/SAXS002"

# Directory where all post-translation steps are located
post_translation_dir: "/Users/bpauw/Code/MOUSEDataPipeline/src"

# Directory where HDF5Translator templates reside
translator_template_dir: "/Users/bpauw/Documents/BAM/Measurements/newMouseTest/Measurements/SAXS002/data/TranslatorConfigurations"

# We use a separate logbook for processing. Make sure to set the "use" flag to True for all entries that should be searched
logbook_file: "/Users/bpauw/Documents/BAM/Measurements/newMouseTest/Measurements/SAXS002/logbooks/Logbook_MOUSE_Dataprocessing.xlsx"