# Define required paths for the MOUSE data pipeline
# Base directory for processing
vsi_root: "/mnt/vsi-db/"

# for testing, we set this to the location of the demo data tree.
saxs_dir: "/mnt/vsi-db/Measurements/SAXS002"

# Directory where all post-translation steps are located
post_translation_dir: "/mnt/vsi-db/Measurements/SAXS002/processingCode/MOUSEDataPipeline_scan_processing/src"

# Directory where HDF5Translator templates reside
translator_template_dir: "/mnt/vsi-db/Measurements/SAXS002/data/TranslatorConfigurations"

stacker_config_file: "/mnt/vsi-db/Measurements/SAXS002/data/StackerConfigurations/stacker_config_xrr.yaml"

# We use a separate logbook for processing. Make sure to set the "use" flag to True for all entries that should be searched
logbook_file: "/mnt/vsi-db/Measurements/SAXS002/logbooks/Logbook_MOUSE_Dataprocessing.xlsx"
